Repository thoth-station/ash-api, pull requests merged in 2020-01, with the labels that each got.

#1 Add Devin to CODEOWNERS
  .github/CODEOWNERS
Labels: approved, size/XS

#5 git pre-commit config
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
Labels: approved, size/M

#2 Add base files for a connexion api
  .gitignore
  Pipfile
  Pipfile.lock
  openapi/ash-api.yaml
  thoth/ash/__init__.py
  thoth/ash/api/__init__.py
  thoth/ash/api/info.py
  thoth/ash/configuration.py
  thoth/ash/openapi_server.py
Labels: approved, size/L

#6 Use typing for describing return type
  thoth/ash/api/info.py
  thoth/ash/openapi_server.py
Labels: approved, size/XS

#7 Remove leftovers from the template project ## This introduces a breaking change
  CHANGELOG.md
  README.md
  README.rst
  app.py
  template/__init__.py
  template/version.py
Labels: approved, size/M

#8 Add gunicorn WSGI HTTP server as a dependency
  Pipfile
  Pipfile.lock
Labels: approved, size/S

#12 Use openapi_server from stub-api - fix for #9
  Pipfile
  Pipfile.lock
  openapi/ash-api.yaml
  thoth/ash/api/words.py
  thoth/ash/configuration.py
  thoth/ash/openapi_server.py
Labels: approved, size/XL
